#**Import libraries**

In [ ]:
# import libraries
import numpy as np
import pandas as pd
import matplotlib as plt
import tensorflow as tf
import keras as k

from sklearn.model_selection import train_test_split

from tensorflow.keras.models import Sequential
from keras.layers.core import Dense

from sklearn.datasets import load_iris

from tensorflow.keras.optimizers import SGD
#from tensorflow.keras.optimizers import Adam

#**Read data**

In [ ]:
#read the data
iris = load_iris()
X = iris.data[:, :]
Y =iris.target

In [ ]:
#shape of features
X_shape= X.shape
X_shape

(150, 4)

In [ ]:
#number of features
n_features= X.shape[1]
n_features

4

In [ ]:
#shape of label
Y.shape

(150,)

In [ ]:
#display the labels
Y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
# display unique variables in the output column
np.unique(Y)

array([0, 1, 2])

#**Split data**

In [ ]:
#split out data
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

#**Model building**

For Iris Dataset it is evident that Neural networkis the best classification method. So we will build simple nural network model for classifying the iris data.


In [ ]:
# construct the model
model = tf.keras.Sequential() 

model.add(Dense(100,input_shape=(n_features,),activation='relu'))
model.add(Dense(50,activation='relu'))
model.add(Dense(3,activation='softmax'))

In [ ]:
# compile the model 
opt = SGD(learning_rate=0.01, momentum=0.9) 
model.compile(optimizer=opt, 
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy']) # for regression ---> (metrics=[mae or mse])

In [ ]:
# fit the model
model.fit(x_train, y_train, epochs=100,validation_data=(x_test, y_test) ,batch_size=32) 

Epoch 1/100
4/4 [==============================] - 1s 65ms/step - loss: 0.9841 - accuracy: 0.3333 - val_loss: 0.9669 - val_accuracy: 0.5667
Epoch 2/100
4/4 [==============================] - 0s 10ms/step - loss: 0.8653 - accuracy: 0.7167 - val_loss: 0.8487 - val_accuracy: 0.5667
Epoch 3/100
4/4 [==============================] - 0s 9ms/step - loss: 0.7545 - accuracy: 0.6917 - val_loss: 0.7964 - val_accuracy: 0.5667
Epoch 4/100
4/4 [==============================] - 0s 9ms/step - loss: 0.6573 - accuracy: 0.7500 - val_loss: 0.5562 - val_accuracy: 0.8333
Epoch 5/100
4/4 [==============================] - 0s 9ms/step - loss: 0.5232 - accuracy: 0.7750 - val_loss: 0.5777 - val_accuracy: 0.5667
Epoch 6/100
4/4 [==============================] - 0s 9ms/step - loss: 0.4579 - accuracy: 0.8250 - val_loss: 0.3893 - val_accuracy: 0.9667
Epoch 7/100
4/4 [==============================] - 0s 8ms/step - loss: 0.3898 - accuracy: 0.9583 - val_loss: 0.4651 - val_accuracy: 0.6333
Epoch 8/100
4/4 [========

In [ ]:
# evaluate the model
loss, acc = model.evaluate(x_test, y_test, verbose=0) # return what i gave it in (compile step)

In [ ]:
print('loss ',loss)
print('accuracy',acc)

loss  0.03040391579270363
accuracy 1.0


In [ ]:
# prediction
y_pred= model.predict(x_test)

In [ ]:
y_pred

array([[2.4530724e-09, 7.5949437e-04, 9.9924052e-01],
       [9.3814480e-04, 9.9762625e-01, 1.4356455e-03],
       [9.9980646e-01, 1.9355891e-04, 1.8862932e-12],
       [2.1367832e-09, 4.9847364e-03, 9.9501532e-01],
       [9.9893647e-01, 1.0635094e-03, 1.2498712e-10],
       [9.5968726e-11, 1.5761757e-04, 9.9984241e-01],
       [9.9928433e-01, 7.1570155e-04, 6.5179057e-11],
       [1.4941329e-04, 9.9665976e-01, 3.1907407e-03],
       [8.2216146e-05, 9.9273807e-01, 7.1797068e-03],
       [1.4026735e-03, 9.9776888e-01, 8.2848244e-04],
       [3.8034088e-08, 1.1508464e-02, 9.8849154e-01],
       [2.9820699e-04, 9.9737775e-01, 2.3240226e-03],
       [1.1041151e-04, 9.7578055e-01, 2.4109038e-02],
       [9.5142816e-05, 9.8488647e-01, 1.5018441e-02],
       [6.7749563e-05, 9.3395936e-01, 6.5972798e-02],
       [9.9930286e-01, 6.9710071e-04, 5.3055099e-11],
       [9.7816090e-05, 9.4690591e-01, 5.2996259e-02],
       [1.1576213e-04, 8.8724232e-01, 1.1264197e-01],
       [9.9799037e-01, 2.009